### ISSUE TITLE
只是好奇

### ISSUE THREAD

**Issue by wujunze** [AC-Union/Issues#1]
你好  我想知道你们做的什么项目 ?   一个开源PHP框架吗?    
还有  你们都是初中的学生吗?  感觉很厉害啊      只是好奇

**Comment by Ray-Eldath** [comment]
抱歉晚回 =-=

诶 只是在做一个Online Judge（在线评测系统）而已，不过工程量其实也挺大得...
其实（包括我在内）大多都是高中生啦
